# Sheldon Plugin Configuration
# https://sheldon.cli.rs/

shell = "zsh" 

# ref: <https://sheldon.cli.rs/Examples.html?highlight=defer#deferred-loading-of-plugins-in-zsh>
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


# =============================
# Plugins
# =============================

# <https://github.com/olets/zsh-window-title>
[plugins.zsh-window-title]
github = "olets/zsh-window-title"
apply = ["defer"]

# <https://github.com/zsh-users/zsh-autosuggestions>
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

# <https://github.com/zdharma-continuum/fast-syntax-highlighting>
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

# <https://github.com/zsh-users/zsh-completions>
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

# <https://github.com/zpm-zsh/ls>
[plugins.zpm-zsh-ls]
github = "zpm-zsh/ls"

# <https://github.com/MichaelAquilina/zsh-you-should-use>
[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

# <https://github.com/alexiszamanidis/zsh-git-fzf>
[plugins.zsh-git-fzf]
github = "alexiszamanidis/zsh-git-fzf"

# <https://github.com/ajeetdsouza/zoxide>
[plugins.zoxide]
github = "ajeetdsouza/zoxide"
use = ["zoxide.plugin.zsh"]

[plugins.compinit]
inline = '''
autoload -Uz compinit
# once a day
for dump in ~/.zcompdump(N.mh+24); do
    compinit; return
done
compinit -C
'''

# ==============================
# Plugin Hooks
# ==============================

[plugins.zsh-you-should-use.hooks]
pre = '''
export YSU_MESSAGE_POSITION="after"
export YSU_MODE=BESTMATCH
export YSU_MESSAGE_FORMAT="$(tput setaf 6)„Äå%command„Äç$(tput sgr0)„ÅÆÊó¢Â≠ò„ÅÆ$(tput setaf 3)„Äå%alias_type„Äç$(tput sgr0)„ÅåË¶ã„Å§„Åã„Å£„Åü„Çà„ÄÇ$(tput setaf 2)„Äå%alias„Äç$(tput sgr0)„Çí‰Ωø„ÅÜ„Å®„ÅÑ„ÅÑ„Çà $(tput sgr0) > üêß"
'''

[plugins.zpm-zsh-ls.hooks]
pre = '''
export ZSH_LS_BACKEND="eza"
export ZSH_LS_DISABLE_GIT=false
'''
