# Starship Configuration
# ã‚«ã‚¹ã‚¿ãƒ ã‚«ãƒ©ãƒ¼ãƒ‘ãƒ¬ãƒƒãƒˆ: https://colormagic.app/ja/palette/671c3f2e53d1e2a13ca7eed2
# ã‚«ãƒ©ãƒ¼å¤‰æ•° (CSS Variablesé¢¨)
# --color-1: #b7e3b0 (æ˜ã‚‹ã„ç·‘)
# --color-2: #a9d6b4 (è–„ã„ç·‘)
# --color-3: #7cb1a3 (ç·‘é’)
# --color-4: #3b7981 (æš—ã„é’ç·‘)
# --color-5: #2a494c (æœ€ã‚‚æš—ã„é’ç·‘)

format = """
[â–‘â–’â–“](#b7e3b0)\
[ğŸ§ ](bg:#b7e3b0 fg:#2a494c)\
[î‚´](bg:#a9d6b4 fg:#b7e3b0)\
$directory\
[î‚´](fg:#a9d6b4 bg:#7cb1a3)\
$git_branch\
$git_status\
[î‚´](fg:#7cb1a3 bg:#3b7981)\
$nodejs\
$rust\
$python\
$golang\
$bun\
[î‚´](fg:#3b7981 bg:#2a494c)\
$time\
[î‚´](fg:#2a494c)\
\n$character"""

command_timeout = 2000
scan_timeout = 30

[directory]
style = "fg:#2a494c bg:#a9d6b4"  # --color-5 fg, --color-2 bg
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#7cb1a3"  # --color-3 bg
format = '[[ $symbol $branch ](fg:#ffffff bg:#7cb1a3)]($style)'

[git_status]
style = "bg:#7cb1a3"  # --color-3 bg
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#7cb1a3)]($style)'

[nodejs]
symbol = "î´"
style = "bg:#3b7981"  # --color-4 bg
format = '[[ $symbol ($version) ](fg:#b7e3b0 bg:#3b7981)]($style)'

[rust]
symbol = "î¨"
style = "bg:#3b7981"  # --color-4 bg
format = '[[ $symbol ($version) ](fg:#b7e3b0 bg:#3b7981)]($style)'

[python]
symbol = "îœ¼"
style = "bg:#3b7981"  # --color-4 bg
format = '[[ $symbol ($version) ](fg:#b7e3b0 bg:#3b7981)]($style)'

[golang]
symbol = "î´"
style = "bg:#3b7981"  # --color-4 bg
format = '[[ $symbol ($version) ](fg:#b7e3b0 bg:#3b7981)]($style)'

[bun]
symbol = "î¯"
style = "bg:#3b7981"  # --color-4 bg
format = '[[ $symbol ($version) ](fg:#b7e3b0  bg:#3b7981)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2a494c"  # --color-5 bg
format = '[[  $time ](fg:#b7e3b0 bg:#2a494c)]($style)'

[character]
success_symbol = '[â¯](bold #b7e3b0)'  # --color-1
error_symbol = '[â¯](bold red)'